<?php

namespace Container9ljdbyC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWishlistControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Account\WishlistController' shared autowired service.
     *
     * @return \App\Controller\Account\WishlistController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Account\\WishlistController'] = $instance = new \App\Controller\Account\WishlistController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Account\\WishlistController', $container));

        return $instance;
    }
}
