<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9ljdbyC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9ljdbyC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9ljdbyC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9ljdbyC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9ljdbyC\App_KernelDevDebugContainer([
    'container.build_hash' => '9ljdbyC',
    'container.build_id' => '40781d4f',
    'container.build_time' => 1734152920,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9ljdbyC');
